spring:
  profiles:
    active: local
    group:
        local: [ local ] # localhost
        prod: [ prod ] # aws ec2
    include: [ admin, oauth, auth, collector, actuator ]
  jpa:
    open-in-view: false
